import { ProductData } from '../interfaces/interfaces';

const products: ProductData[] = [
  {
    id: 0,
    name: 'Accent Chair',
    image: './images/accent-chair.jpg',
    price: 260,
    category: 'Office',
    company: 'Marcos',
    color: 'green',
    amount: 7,
    popular: true,
    isCart: false
  },
  {
    id: 1,
    name: 'Vase Table',
    image: './images/vase-table.jpg',
    price: 1210,
    category: 'Office',
    company: 'Marcos',
    color: 'red',
    amount: 5,
    popular: true,
    isCart: false
  },
  {
    id: 2,
    name: 'High-Back Bench',
    image: './images/high-back-bench.jpg',
    price: 400,
    category: 'Office',
    company: 'Ikea',
    color: 'green',
    amount: 2,
    popular: true,
    isCart: false
  },
  {
    id: 3,
    name: 'Modern Desk',
    image: './images/modern-desk.jpg',
    price: 400,
    category: 'Office',
    company: 'Ikea',
    color: 'green',
    amount: 3,
    popular: true,
    isCart: false
  },
  {
    id: 4,
    name: 'Modern Poster',
    image: './images/modern-poster.jpg',
    price: 31,
    category: 'Living Room',
    company: 'Liddy',
    color: 'black',
    amount: 15,
    popular: false,
    isCart: false
  },
  {
    id: 5,
    name: 'Albany Sectional',
    image: './images/albany-sectional.jpg',
    price: 1099,
    category: 'Living Room',
    company: 'Liddy',
    color: 'black',
    amount: 21,
    popular: false,
    isCart: false
  },
  {
    id: 6,
    name: 'Utopia Sofa',
    image: './images/utopia-sofa.jpg',
    price: 800,
    category: 'Living Room',
    company: 'Liddy',
    color: 'red',
    amount: 6,
    popular: false,
    isCart: false
  },
  {
    id: 7,
    name: 'Simple Chair',
    image: './images/simple-chair.jpg',
    price: 1099,
    category: 'Living Room',
    company: 'Liddy',
    color: 'blue',
    amount: 7,
    popular: false,
    isCart: false
  },
  {
    id: 8,
    name: 'Albany Table',
    image: './images/albany-table.jpg',
    price: 3099,
    category: 'Kitchen',
    company: 'Liddy',
    color: 'yellow',
    amount: 8,
    popular: false,
    isCart: false
  },
  {
    id: 9,
    name: 'Wooden Desk',
    image: './images/wooden-desk.jpg',
    price: 400,
    category: 'Office',
    company: 'Ikea',
    color: 'green',
    amount: 1,
    popular: true,
    isCart: false
  },
  {
    id: 10,
    name: 'Bar Stool',
    image: './images/bar-stool.jpg',
    price: 41,
    category: 'Dining',
    company: 'Liddy',
    color: 'black',
    amount: 10,
    popular: false,
    isCart: false
  },
  {
    id: 11,
    name: 'Armchair',
    image: './images/armchair.jpg',
    price: 125,
    category: 'Bedroom',
    company: 'Marcos',
    color: 'green',
    amount: 6,
    popular: false,
    isCart: false
  },
  {
    id: 12,
    name: 'Suede Armchair',
    image: './images/suede-armchair.jpg',
    price: 159,
    category: 'Office',
    company: 'Caressa',
    color: 'yellow',
    amount: 9,
    popular: false,
    isCart: false
  },
  {
    id: 13,
    name: 'Leather Chair',
    image: './images/leather-chair.jpg',
    price: 200,
    category: 'Bedroom',
    company: 'Caressa',
    color: 'red',
    amount: 7,
    popular: false,
    isCart: false
  },
  {
    id: 14,
    name: 'Emperor Bed',
    image: './images/emperor-bed.jpg',
    price: 239,
    category: 'Bedroom',
    company: 'Ikea',
    color: 'black',
    amount: 12,
    popular: false,
    isCart: false
  },
  {
    id: 15,
    name: 'Shelf',
    image: './images/shelf.jpg',
    price: 309,
    category: 'Living Room',
    company: 'Ikea',
    color: 'green',
    amount: 16,
    popular: false,
    isCart: false
  },
  {
    id: 16,
    name: 'Modern Bookshelf',
    image: './images/modern-bookshelf.jpg',
    price: 319,
    category: 'Kids',
    company: 'Caressa',
    color: 'yellow',
    amount: 17,
    popular: false,
    isCart: false
  },
  {
    id: 17,
    name: 'Dining Table',
    image: './images/dining-table.jpg',
    price: 429,
    category: 'Dining',
    company: 'Ikea',
    color: 'red',
    amount: 14,
    popular: false,
    isCart: false
  },
  {
    id: 18,
    name: 'Entertainment Center',
    image: './images/entertainment-center.jpg',
    price: 599,
    category: 'Living Room',
    company: 'Caressa',
    color: 'black',
    amount: 13,
    popular: false,
    isCart: false
  },
  {
    id: 19,
    name: 'Leather Sofa',
    image: './images/leather-sofa.jpg',
    price: 999,
    category: 'Office',
    company: 'Caressa',
    color: 'blue',
    amount: 12,
    popular: false,
    isCart: false
  },
  {
    id: 20,
    name: 'Sofa Set',
    image: './images/sofa-set.jpg',
    price: 1299,
    category: 'Living Room',
    company: 'Marcos',
    color: 'yellow',
    amount: 8,
    popular: true,
    isCart: false
  },
  {
    id: 21,
    name: 'Wooden Bed',
    image: './images/wooden-bed.jpg',
    price: 2500,
    category: 'Bedroom',
    company: 'Ikea',
    color: 'black',
    amount: 12,
    popular: false,
    isCart: false
  },
  {
    id: 22,
    name: 'Wooden Table',
    image: './images/wooden-table.jpg',
    price: 2349,
    category: 'Kitchen',
    company: 'Caressa',
    color: 'red',
    amount: 2,
    popular: true,
    isCart: false
  },
];

export default products;